name: 'Modular Archive Manager'
description: 'Packs or unpacks preserving file permissions'

inputs:
  path:
    description: 'Path to the folder to pack. Leave blank to unpack.'
    required: false
    default: ''
  artifact_name:
    description: 'The GitHub Artifact storage identifier'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set internal variables
      shell: bash
      run: echo "ARCHIVE_NAME=action_payload.tgz" >> $GITHUB_ENV

    - name: Pack directory into Tarball
      if: ${{ inputs.path != '' }}
      shell: bash
      run: tar cvfz ${{ env.ARCHIVE_NAME }} "${{ inputs.path }}"

    - name: Upload the created archive
      if: ${{ inputs.path != '' }}
      uses: actions/upload-artifact@v7
      with:
        name: ${{ inputs.artifact_name }}
        path: ${{ env.ARCHIVE_NAME }}

    # ==========================================
    # DOWNLOAD & UNPACK
    # ==========================================
    - name: Download existing archive
      if: ${{ inputs.path == '' }}
      uses: actions/download-artifact@v8
      with:
        name: ${{ inputs.artifact_name }}

    - name: Unpack Tarball
      if: ${{ inputs.path == '' }}
      shell: bash
      run: |
        tar xvfz ${{ env.ARCHIVE_NAME }}
        rm -f ${{ env.ARCHIVE_NAME }}
