# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Documentation

permissions:
  contents: write
  pages: write
  pull-requests: write
  id-token: write

on:
  # pull_request_target:
  #   types: [opened, reopened, synchronize] # Handles forked PRs
  workflow_dispatch:
    inputs:
      create_docker_image:
        description: '[Re]create the docker image ubuntu-test'
        required: true
        type: boolean
        default: false
  push:
    branches:
      - main # docs are built only on push to main branch, for feature branches there are PR builds
  # merge_group:
  #   types: [checks_requested]
  # release:
    #   types: [created]
env:
  ARTIFACT_NAME: "test"
  ARCHIVE_NAME: "bla.tgz"

jobs:
  make_image:
    if: ${{ inputs.create_docker_image }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Login to CR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker img
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          push: true
          tags: ghcr.io/${{ github.repository }}/ubuntu-tree
  pre_docs:
    if: |
      always() &&
      (needs.make_image.result == 'success' || needs.make_image.result == 'skipped')
    needs: make_image
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/ubuntu-tree
    steps:
      - name: Create distributed
        run: |
          mkdir -p bla
          echo test > bla/test.txt
          cat bla/test.txt
          echo 'echo abc' > bla/test.sh
          chmod +x bla/test.sh
      - run: tar czf $ARCHIVE_NAME ./bla
      - uses: actions/upload-artifact@v7
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARCHIVE_NAME }}
      - name: Show workspace
        run: |
          pwd
          echo "$GITHUB_WORKSPACE"
          ls -Rali
  docs:
    if: ${{ !failure() && !cancelled() }}
    needs: pre_docs
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/ubuntu-tree
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: ${{ env.ARTIFACT_NAME }}
      - run: tar xvfz $ARCHIVE_NAME
      - run: |
          tree .
          ./bla/test.sh
  # docs-build:
  #   needs: pre_docs
  #   uses: eclipse-score/cicd-workflows/.github/workflows/docs.yml@829b3e11ccbf924a5782f7bfed647cb1619fdf78 # v0.0.1
  #   permissions:
  #     contents: write
  #     pages: write
  #     pull-requests: write
  #     id-token: write
  #   with:
  #     bazel-target: "//:docs -- --github_user=${{ github.repository_owner }} --github_repo=${{ github.event.repository.name }}"
  #     retention-days: 3
